### PR TITLE
Badge

### PR DESCRIPTION
**Pull request by BALAJI141031**

### CODE REVIEW

**Review by Ananyamadhu08 — APPROVED** [review]
looks good to me 🚀

**Comment by ShrutiLakhani** [comment]
Please use shorthand for border styling

**Comment by m26unkwn** [comment]
Your Badge is stunning

**Comment by BALAJI141031** [comment]
> 

@ShrutiLakhani  can you explain it bit more

**Comment by BALAJI141031** [comment]
@ShrutiLakhani yeah got it what you are saying after viewing button pr thank you

**Comment by BALAJI141031** [comment]
@m26unkwn and @Ananyamadhu08 thank you

**Pull request merged**
